// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseDialog: typeof import('./../src/components/BaseDialog.vue')['default']
    BasePanel: typeof import('./../src/components/BasePanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCode: typeof import('./../src/components/TheCode.vue')['default']
    TheImage: typeof import('./../src/components/TheImage.vue')['default']
    TheThree: typeof import('./../src/components/TheThree.vue')['default']
  }
}

export {}
